<option value="AED" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='AED') ? 'selected' : ''; ?>>AED</option>
<option value="AFN" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='AFN') ? 'selected' : ''; ?>>AFN</option>
<option value="ALL" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='ALL') ? 'selected' : ''; ?>>ALL</option>
<option value="AMD" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='AMD') ? 'selected' : ''; ?>>AMD</option>
<option value="ANG" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='ANG') ? 'selected' : ''; ?>>ANG</option>
<option value="AOA" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='AOA') ? 'selected' : ''; ?>>AOA</option>
<option value="ARS" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='ARS') ? 'selected' : ''; ?>>ARS</option>
<option value="AUD" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='AUD') ? 'selected' : ''; ?>>AUD</option>
<option value="AWG" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='AWG') ? 'selected' : ''; ?>>AWG</option>
<option value="AZN" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='AZN') ? 'selected' : ''; ?>>AZN</option>
<option value="BAM" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='BAM') ? 'selected' : ''; ?>>BAM</option>
<option value="BBD" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='BBD') ? 'selected' : ''; ?>>BBD</option>
<option value="BDT" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='BDT') ? 'selected' : ''; ?>>BDT</option>
<option value="BGN" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='BGN') ? 'selected' : ''; ?>>BGN</option>
<option value="BHD" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='BHD') ? 'selected' : ''; ?>>BHD</option>
<option value="BIF" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='BIF') ? 'selected' : ''; ?>>BIF</option>
<option value="BMD" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='BMD') ? 'selected' : ''; ?>>BMD</option>
<option value="BND" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='BND') ? 'selected' : ''; ?>>BND</option>
<option value="BOB" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='BOB') ? 'selected' : ''; ?>>BOB</option>
<option value="BRL" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='BRL') ? 'selected' : ''; ?>>BRL</option>
<option value="BSD" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='BSD') ? 'selected' : ''; ?>>BSD</option>
<option value="BTN" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='BTN') ? 'selected' : ''; ?>>BTN</option>
<option value="BWP" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='BWP') ? 'selected' : ''; ?>>BWP</option>
<option value="BYN" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='BYN') ? 'selected' : ''; ?>>BYN</option>
<option value="BYR" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='BYR') ? 'selected' : ''; ?>>BYR</option>
<option value="BZD" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='BZD') ? 'selected' : ''; ?>>BZD</option>
<option value="CAD" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='CAD') ? 'selected' : ''; ?>>CAD</option>
<option value="CDF" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='CDF') ? 'selected' : ''; ?>>CDF</option>
<option value="CHF" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='CHF') ? 'selected' : ''; ?>>CHF</option>
<option value="CLF" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='CLF') ? 'selected' : ''; ?>>CLF</option>
<option value="CLP" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='CLP') ? 'selected' : ''; ?>>CLP</option>
<option value="CNH" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='CNH') ? 'selected' : ''; ?>>CNH</option>
<option value="CNY" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='CNY') ? 'selected' : ''; ?>>CNY</option>
<option value="COP" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='COP') ? 'selected' : ''; ?>>COP</option>
<option value="CRC" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='CRC') ? 'selected' : ''; ?>>CRC</option>
<option value="CUC" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='CUC') ? 'selected' : ''; ?>>CUC</option>
<option value="CUP" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='CUP') ? 'selected' : ''; ?>>CUP</option>
<option value="CVE" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='CVE') ? 'selected' : ''; ?>>CVE</option>
<option value="CZK" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='CZK') ? 'selected' : ''; ?>>CZK</option>
<option value="DASH" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='DASH') ? 'selected' : ''; ?>>DASH</option>
<option value="DJF" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='DJF') ? 'selected' : ''; ?>>DJF</option>
<option value="DKK" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='DKK') ? 'selected' : ''; ?>>DKK</option>
<option value="DOP" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='DOP') ? 'selected' : ''; ?>>DOP</option>
<option value="DZD" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='DZD') ? 'selected' : ''; ?>>DZD</option>
<option value="EEK" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='EEK') ? 'selected' : ''; ?>>EEK</option>
<option value="EGP" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='EGP') ? 'selected' : ''; ?>>EGP</option>
<option value="ERN" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='ERN') ? 'selected' : ''; ?>>ERN</option>
<option value="ETB" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='ETB') ? 'selected' : ''; ?>>ETB</option>
<option value="ETH" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='ETH') ? 'selected' : ''; ?>>ETH</option>
<option value="EUR" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='EUR') ? 'selected' : ''; ?>>EUR</option>
<option value="FJD" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='FJD') ? 'selected' : ''; ?>>FJD</option>
<option value="FKP" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='FKP') ? 'selected' : ''; ?>>FKP</option>
<option value="GBP" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='GBP') ? 'selected' : ''; ?>>GBP</option>
<option value="GEL" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='GEL') ? 'selected' : ''; ?>>GEL</option>
<option value="GGP" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='GGP') ? 'selected' : ''; ?>>GGP</option>
<option value="GHS" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='GHS') ? 'selected' : ''; ?>>GHS</option>
<option value="GIP" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='GIP') ? 'selected' : ''; ?>>GIP</option>
<option value="GMD" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='GMD') ? 'selected' : ''; ?>>GMD</option>
<option value="GNF" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='GNF') ? 'selected' : ''; ?>>GNF</option>
<option value="GTQ" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='GTQ') ? 'selected' : ''; ?>>GTQ</option>
<option value="GYD" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='GYD') ? 'selected' : ''; ?>>GYD</option>
<option value="HKD" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='HKD') ? 'selected' : ''; ?>>HKD</option>
<option value="HNL" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='HNL') ? 'selected' : ''; ?>>HNL</option>
<option value="HRK" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='HRK') ? 'selected' : ''; ?>>HRK</option>
<option value="HTG" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='HTG') ? 'selected' : ''; ?>>HTG</option>
<option value="HUF" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='HUF') ? 'selected' : ''; ?>>HUF</option>
<option value="IDR" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='IDR') ? 'selected' : ''; ?>>IDR</option>
<option value="ILS" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='ILS') ? 'selected' : ''; ?>>ILS</option>
<option value="IMP" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='IMP') ? 'selected' : ''; ?>>IMP</option>
<option value="INR" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='INR') ? 'selected' : ''; ?>>INR</option>
<option value="IQD" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='IQD') ? 'selected' : ''; ?>>IQD</option>
<option value="IRR" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='IRR') ? 'selected' : ''; ?>>IRR</option>
<option value="ISK" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='ISK') ? 'selected' : ''; ?>>ISK</option>
<option value="JEP" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='JEP') ? 'selected' : ''; ?>>JEP</option>
<option value="JMD" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='JMD') ? 'selected' : ''; ?>>JMD</option>
<option value="JOD" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='JOD') ? 'selected' : ''; ?>>JOD</option>
<option value="JPY" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='JPY') ? 'selected' : ''; ?>>JPY</option>
<option value="KES" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='KES') ? 'selected' : ''; ?>>KES</option>
<option value="KGS" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='KGS') ? 'selected' : ''; ?>>KGS</option>
<option value="KHR" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='KHR') ? 'selected' : ''; ?>>KHR</option>
<option value="KMF" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='KMF') ? 'selected' : ''; ?>>KMF</option>
<option value="KPW" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='KPW') ? 'selected' : ''; ?>>KPW</option>
<option value="KRW" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='KRW') ? 'selected' : ''; ?>>KRW</option>
<option value="KWD" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='KWD') ? 'selected' : ''; ?>>KWD</option>
<option value="KYD" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='KYD') ? 'selected' : ''; ?>>KYD</option>
<option value="KZT" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='KZT') ? 'selected' : ''; ?>>KZT</option>
<option value="LAK" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='LAK') ? 'selected' : ''; ?>>LAK</option>
<option value="LBP" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='LBP') ? 'selected' : ''; ?>>LBP</option>
<option value="LKR" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='LKR') ? 'selected' : ''; ?>>LKR</option>
<option value="LRD" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='LRD') ? 'selected' : ''; ?>>LRD</option>
<option value="LSL" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='LSL') ? 'selected' : ''; ?>>LSL</option>
<option value="LTC" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='LTC') ? 'selected' : ''; ?>>LTC</option>
<option value="LTL" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='LTL') ? 'selected' : ''; ?>>LTL</option>
<option value="LVL" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='LVL') ? 'selected' : ''; ?>>LVL</option>
<option value="LYD" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='LYD') ? 'selected' : ''; ?>>LYD</option>
<option value="MAD" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='MAD') ? 'selected' : ''; ?>>MAD</option>
<option value="MDL" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='MDL') ? 'selected' : ''; ?>>MDL</option>
<option value="MGA" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='MGA') ? 'selected' : ''; ?>>MGA</option>
<option value="MKD" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='MKD') ? 'selected' : ''; ?>>MKD</option>
<option value="MMK" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='MMK') ? 'selected' : ''; ?>>MMK</option>
<option value="MNT" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='MNT') ? 'selected' : ''; ?>>MNT</option>
<option value="MOP" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='MOP') ? 'selected' : ''; ?>>MOP</option>
<option value="MRO" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='MRO') ? 'selected' : ''; ?>>MRO</option>
<option value="MRU" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='MRU') ? 'selected' : ''; ?>>MRU</option>
<option value="MTL" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='MTL') ? 'selected' : ''; ?>>MTL</option>
<option value="MUR" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='MUR') ? 'selected' : ''; ?>>MUR</option>
<option value="MVR" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='MVR') ? 'selected' : ''; ?>>MVR</option>
<option value="MWK" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='MWK') ? 'selected' : ''; ?>>MWK</option>
<option value="MXN" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='MXN') ? 'selected' : ''; ?>>MXN</option>
<option value="MYR" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='MYR') ? 'selected' : ''; ?>>MYR</option>
<option value="MZN" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='MZN') ? 'selected' : ''; ?>>MZN</option>
<option value="NAD" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='NAD') ? 'selected' : ''; ?>>NAD</option>
<option value="NGN" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='NGN') ? 'selected' : ''; ?>>NGN</option>
<option value="NIO" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='NIO') ? 'selected' : ''; ?>>NIO</option>
<option value="NOK" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='NOK') ? 'selected' : ''; ?>>NOK</option>
<option value="NPR" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='NPR') ? 'selected' : ''; ?>>NPR</option>
<option value="NZD" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='NZD') ? 'selected' : ''; ?>>NZD</option>
<option value="OMR" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='OMR') ? 'selected' : ''; ?>>OMR</option>
<option value="PAB" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='PAB') ? 'selected' : ''; ?>>PAB</option>
<option value="PEN" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='PEN') ? 'selected' : ''; ?>>PEN</option>
<option value="PGK" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='PGK') ? 'selected' : ''; ?>>PGK</option>
<option value="PHP" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='PHP') ? 'selected' : ''; ?>>PHP</option>
<option value="PKR" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='PKR') ? 'selected' : ''; ?>>PKR</option>
<option value="PLN" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='PLN') ? 'selected' : ''; ?>>PLN</option>
<option value="PYG" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='PYG') ? 'selected' : ''; ?>>PYG</option>
<option value="QAR" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='QAR') ? 'selected' : ''; ?>>QAR</option>
<option value="RON" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='RON') ? 'selected' : ''; ?>>RON</option>
<option value="RSD" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='RSD') ? 'selected' : ''; ?>>RSD</option>
<option value="RUB" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='RUB') ? 'selected' : ''; ?>>RUB</option>
<option value="RWF" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='RWF') ? 'selected' : ''; ?>>RWF</option>
<option value="SAR" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='SAR') ? 'selected' : ''; ?>>SAR</option>
<option value="SBD" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='SBD') ? 'selected' : ''; ?>>SBD</option>
<option value="SCR" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='SCR') ? 'selected' : ''; ?>>SCR</option>
<option value="SDG" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='SDG') ? 'selected' : ''; ?>>SDG</option>
<option value="SEK" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='SEK') ? 'selected' : ''; ?>>SEK</option>
<option value="SGD" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='SGD') ? 'selected' : ''; ?>>SGD</option>
<option value="SHP" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='SHP') ? 'selected' : ''; ?>>SHP</option>
<option value="SLL" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='SLL') ? 'selected' : ''; ?>>SLL</option>
<option value="SOS" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='SOS') ? 'selected' : ''; ?>>SOS</option>
<option value="SRD" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='SRD') ? 'selected' : ''; ?>>SRD</option>
<option value="SSP" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='SSP') ? 'selected' : ''; ?>>SSP</option>
<option value="STD" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='STD') ? 'selected' : ''; ?>>STD</option>
<option value="STN" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='STN') ? 'selected' : ''; ?>>STN</option>
<option value="SVC" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='SVC') ? 'selected' : ''; ?>>SVC</option>
<option value="SYP" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='SYP') ? 'selected' : ''; ?>>SYP</option>
<option value="SZL" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='SZL') ? 'selected' : ''; ?>>SZL</option>
<option value="THB" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='THB') ? 'selected' : ''; ?>>THB</option>
<option value="TJS" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='TJS') ? 'selected' : ''; ?>>TJS</option>
<option value="TMT" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='TMT') ? 'selected' : ''; ?>>TMT</option>
<option value="TND" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='TND') ? 'selected' : ''; ?>>TND</option>
<option value="TOP" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='TOP') ? 'selected' : ''; ?>>TOP</option>
<option value="TRY" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='TRY') ? 'selected' : ''; ?>>TRY</option>
<option value="TTD" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='TTD') ? 'selected' : ''; ?>>TTD</option>
<option value="TWD" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='TWD') ? 'selected' : ''; ?>>TWD</option>
<option value="TZS" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='TZS') ? 'selected' : ''; ?>>TZS</option>
<option value="UAH" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='UAH') ? 'selected' : ''; ?>>UAH</option>
<option value="UGX" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='UGX') ? 'selected' : ''; ?>>UGX</option>
<option value="USD" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='USD') ? 'selected' : ''; ?>>USD</option>
<option value="UYU" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='UYU') ? 'selected' : ''; ?>>UYU</option>
<option value="UZS" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='UZS') ? 'selected' : ''; ?>>UZS</option>
<option value="VES" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='VES') ? 'selected' : ''; ?>>VES</option>
<option value="VND" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='VND') ? 'selected' : ''; ?>>VND</option>
<option value="VUV" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='VUV') ? 'selected' : ''; ?>>VUV</option>
<option value="WST" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='WST') ? 'selected' : ''; ?>>WST</option>
<option value="XAF" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='XAF') ? 'selected' : ''; ?>>XAF</option>
<option value="XAG" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='XAG') ? 'selected' : ''; ?>>XAG</option>
<option value="XAR" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='XAR') ? 'selected' : ''; ?>>XAR</option>
<option value="XAU" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='XAU') ? 'selected' : ''; ?>>XAU</option>
<option value="XCD" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='XCD') ? 'selected' : ''; ?>>XCD</option>
<option value="XDR" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='XDR') ? 'selected' : ''; ?>>XDR</option>
<option value="XMR" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='XMR') ? 'selected' : ''; ?>>XMR</option>
<option value="XOF" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='XOF') ? 'selected' : ''; ?>>XOF</option>
<option value="XPD" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='XPD') ? 'selected' : ''; ?>>XPD</option>
<option value="XPF" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='XPF') ? 'selected' : ''; ?>>XPF</option>
<option value="XPT" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='XPT') ? 'selected' : ''; ?>>XPT</option>
<option value="XRP" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='XRP') ? 'selected' : ''; ?>>XRP</option>
<option value="YER" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='YER') ? 'selected' : ''; ?>>YER</option>
<option value="ZAR" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='ZAR') ? 'selected' : ''; ?>>ZAR</option>
<option value="ZMK" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='ZMK') ? 'selected' : ''; ?>>ZMK</option>
<option value="ZMW" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='ZMW') ? 'selected' : ''; ?>>ZMW</option>
<option value="ZWL" <?php echo (!empty($_GET['currency'])&&strtoupper($_GET['currency'])=='ZWL') ? 'selected' : ''; ?>>ZWL</option>